apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  labels:
    app: minecraft-service
spec:
  selector:
    app: minecraft-server
  ports:
    - name: server
      protocol: TCP
      port: 25565
      targetPort: 25565
    - name: utility
      protocol: TCP
      port: 25575
      targetPort: 25575
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: minecraft-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft-server        
    spec:
      containers:
      - name: minecraft-server
        image: openhack/minecraft-server:1.0
        env:
        - name: EULA
          value: "TRUE"
        ports:
        - containerPort: 25565
        - containerPort: 25575
        imagePullPolicy: Always
      volumeMounts:
        - name: azure
          mountPath: /data
      volumes:
        - name: azure
          persistentVolumeClaim:
            claimName: azurefile